services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiMjml\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Exception/*'

  Maispace\MaiMjml\Service\MjmlService:
    public: true

  Maispace\MaiMjml\Middleware\MjmlMiddleware:
    public: true
